# Generated by Django 5.0.6 on 2025-10-02 23:05

import CVapp.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('offer', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Resume',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.CharField(max_length=10)),
                ('name', models.CharField(max_length=100)),
                ('vacancy_text', models.CharField(max_length=1000)),
                ('extracted_text', models.TextField()),
                ('upgraded_cv', models.TextField()),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('embedding', models.BinaryField(default=CVapp.models._default_embedding)),
                ('image', models.ImageField(blank=True, null=True, upload_to='images/resumes/')),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.user')),
            ],
        ),
        migrations.CreateModel(
            name='Applied_resume',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('match_rate', models.FloatField()),
                ('state', models.CharField(choices=[('applied', 'Applied'), ('interviewed', 'Interviewed'), ('rejected', 'Rejected')], default='applied', max_length=20)),
                ('feedback', models.TextField(blank=True, null=True)),
                ('applied_at', models.DateTimeField(auto_now_add=True)),
                ('vacancy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='offer.vacancy')),
                ('resume', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CVapp.resume')),
            ],
        ),
        migrations.CreateModel(
            name='Saved_vacancy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('saved_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.user')),
                ('vacancy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='offer.vacancy')),
            ],
        ),
    ]
