from django.db import models
from users.models import User


class Notification(models.Model):
    """Simple notification model for a user.

    Stores a textual message for a user and whether it has been
    read.  Notifications are typically generated by events in other
    apps (e.g., accepting or rejecting a resume).
    """

    user = models.ForeignKey(User, on_delete=models.CASCADE, related_name="notifications")
    message = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)
    read = models.BooleanField(default=False)

    def __str__(self) -> str:
        return f"Notification for {self.user.username}: {self.message[:20]}..."